/**
 * @module monaco-editor/themes
 *
 * Built-in Monaco themes. All themes follow the MonacoThemeDef interface
 * and are auto-registered when the editor mounts.
 *
 * To add a custom theme:
 *   import { registerTheme, type MonacoThemeDef } from "@/modules/monaco-editor";
 *
 *   const myTheme: MonacoThemeDef = { id: "my-theme", ... };
 *   // Register in onBeforeMount or on the raw monaco instance
 */

import type { MonacoThemeDef } from "../types";

// ── One Dark ─────────────────────────────────────────────────

export const oneDark: MonacoThemeDef = {
  id: "one-dark",
  name: "One Dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "5c6370", fontStyle: "italic" },
    { token: "keyword", foreground: "c678dd" },
    { token: "string", foreground: "98c379" },
    { token: "number", foreground: "d19a66" },
    { token: "type", foreground: "e5c07b" },
    { token: "function", foreground: "61afef" },
    { token: "variable", foreground: "e06c75" },
    { token: "constant", foreground: "d19a66" },
    { token: "operator", foreground: "56b6c2" },
    { token: "tag", foreground: "e06c75" },
    { token: "attribute.name", foreground: "d19a66" },
    { token: "attribute.value", foreground: "98c379" },
    { token: "delimiter", foreground: "abb2bf" },
    { token: "regexp", foreground: "56b6c2" },
  ],
  colors: {
    "editor.background": "#282c34",
    "editor.foreground": "#abb2bf",
    "editor.lineHighlightBackground": "#2c313a",
    "editor.selectionBackground": "#3e4451",
    "editorCursor.foreground": "#528bff",
    "editorWhitespace.foreground": "#3b4048",
    "editorLineNumber.foreground": "#495162",
    "editorLineNumber.activeForeground": "#abb2bf",
    "editorIndentGuide.background": "#3b4048",
    "editorIndentGuide.activeBackground": "#c8c8c859",
    "editorBracketMatch.background": "#515a6b40",
    "editorBracketMatch.border": "#515a6b99",
    "editor.findMatchBackground": "#d19a6644",
    "editor.findMatchHighlightBackground": "#ffffff22",
    "editorOverviewRuler.border": "#282c34",
    "scrollbarSlider.background": "#4e566680",
    "scrollbarSlider.hoverBackground": "#5a637580",
    "scrollbarSlider.activeBackground": "#747d9180",
  },
};

// ── Dracula ──────────────────────────────────────────────────

export const dracula: MonacoThemeDef = {
  id: "dracula",
  name: "Dracula",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6272a4", fontStyle: "italic" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "string", foreground: "f1fa8c" },
    { token: "number", foreground: "bd93f9" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "function", foreground: "50fa7b" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "constant", foreground: "bd93f9" },
    { token: "operator", foreground: "ff79c6" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "regexp", foreground: "ff5555" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#44475a75",
    "editor.selectionBackground": "#44475a",
    "editorCursor.foreground": "#f8f8f2",
    "editorWhitespace.foreground": "#44475a",
    "editorLineNumber.foreground": "#6272a4",
    "editorLineNumber.activeForeground": "#f8f8f2",
    "editorIndentGuide.background": "#44475a60",
    "editorIndentGuide.activeBackground": "#6272a4",
    "editorBracketMatch.background": "#44475a80",
    "editorBracketMatch.border": "#bd93f9",
    "editor.findMatchBackground": "#ffb86c44",
    "editor.findMatchHighlightBackground": "#ffffff22",
    "editorOverviewRuler.border": "#282a36",
    "scrollbarSlider.background": "#44475a80",
    "scrollbarSlider.hoverBackground": "#44475aaa",
    "scrollbarSlider.activeBackground": "#44475acc",
  },
};

// ── GitHub Dark ──────────────────────────────────────────────

export const githubDark: MonacoThemeDef = {
  id: "github-dark",
  name: "GitHub Dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "8b949e", fontStyle: "italic" },
    { token: "keyword", foreground: "ff7b72" },
    { token: "string", foreground: "a5d6ff" },
    { token: "number", foreground: "79c0ff" },
    { token: "type", foreground: "ffa657" },
    { token: "function", foreground: "d2a8ff" },
    { token: "variable", foreground: "ffa657" },
    { token: "constant", foreground: "79c0ff" },
    { token: "operator", foreground: "ff7b72" },
    { token: "tag", foreground: "7ee787" },
    { token: "attribute.name", foreground: "79c0ff" },
    { token: "attribute.value", foreground: "a5d6ff" },
    { token: "delimiter", foreground: "c9d1d9" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "editor.lineHighlightBackground": "#161b22",
    "editor.selectionBackground": "#264f78",
    "editorCursor.foreground": "#c9d1d9",
    "editorWhitespace.foreground": "#21262d",
    "editorLineNumber.foreground": "#484f58",
    "editorLineNumber.activeForeground": "#c9d1d9",
    "editorIndentGuide.background": "#21262d",
    "editorIndentGuide.activeBackground": "#30363d",
    "editorBracketMatch.background": "#264f7850",
    "editorBracketMatch.border": "#79c0ff50",
    "editor.findMatchBackground": "#ffa65733",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#0d1117",
    "scrollbarSlider.background": "#484f5860",
    "scrollbarSlider.hoverBackground": "#484f5880",
    "scrollbarSlider.activeBackground": "#484f58a0",
  },
};

// ── Monokai ──────────────────────────────────────────────────

export const monokai: MonacoThemeDef = {
  id: "monokai",
  name: "Monokai",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "75715e", fontStyle: "italic" },
    { token: "keyword", foreground: "f92672" },
    { token: "string", foreground: "e6db74" },
    { token: "number", foreground: "ae81ff" },
    { token: "type", foreground: "66d9ef", fontStyle: "italic" },
    { token: "function", foreground: "a6e22e" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "constant", foreground: "ae81ff" },
    { token: "operator", foreground: "f92672" },
    { token: "tag", foreground: "f92672" },
    { token: "attribute.name", foreground: "a6e22e" },
    { token: "attribute.value", foreground: "e6db74" },
    { token: "delimiter", foreground: "f8f8f2" },
  ],
  colors: {
    "editor.background": "#272822",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#3e3d32",
    "editor.selectionBackground": "#49483e",
    "editorCursor.foreground": "#f8f8f0",
    "editorWhitespace.foreground": "#3b3a32",
    "editorLineNumber.foreground": "#90908a",
    "editorLineNumber.activeForeground": "#c2c2bf",
    "editorIndentGuide.background": "#3b3a32",
    "editorIndentGuide.activeBackground": "#767771",
    "editorBracketMatch.background": "#49483e80",
    "editorBracketMatch.border": "#a6e22e50",
    "editor.findMatchBackground": "#e6db7444",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#272822",
    "scrollbarSlider.background": "#49483e80",
    "scrollbarSlider.hoverBackground": "#49483ea0",
    "scrollbarSlider.activeBackground": "#49483ec0",
  },
};

// ── Nord ─────────────────────────────────────────────────────

export const nord: MonacoThemeDef = {
  id: "nord",
  name: "Nord",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "616e88", fontStyle: "italic" },
    { token: "keyword", foreground: "81a1c1" },
    { token: "string", foreground: "a3be8c" },
    { token: "number", foreground: "b48ead" },
    { token: "type", foreground: "8fbcbb" },
    { token: "function", foreground: "88c0d0" },
    { token: "variable", foreground: "d8dee9" },
    { token: "constant", foreground: "b48ead" },
    { token: "operator", foreground: "81a1c1" },
    { token: "tag", foreground: "81a1c1" },
    { token: "attribute.name", foreground: "8fbcbb" },
    { token: "attribute.value", foreground: "a3be8c" },
    { token: "delimiter", foreground: "eceff4" },
  ],
  colors: {
    "editor.background": "#2e3440",
    "editor.foreground": "#d8dee9",
    "editor.lineHighlightBackground": "#3b4252",
    "editor.selectionBackground": "#434c5e",
    "editorCursor.foreground": "#d8dee9",
    "editorWhitespace.foreground": "#434c5e60",
    "editorLineNumber.foreground": "#4c566a",
    "editorLineNumber.activeForeground": "#d8dee9",
    "editorIndentGuide.background": "#434c5e60",
    "editorIndentGuide.activeBackground": "#4c566a",
    "editorBracketMatch.background": "#434c5e80",
    "editorBracketMatch.border": "#88c0d050",
    "editor.findMatchBackground": "#88c0d044",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#2e3440",
    "scrollbarSlider.background": "#4c566a80",
    "scrollbarSlider.hoverBackground": "#4c566aa0",
    "scrollbarSlider.activeBackground": "#4c566ac0",
  },
};

// ── Synthwave '84 ────────────────────────────────────────────

export const synthwave84: MonacoThemeDef = {
  id: "synthwave-84",
  name: "Synthwave '84",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "8e8e8e", fontStyle: "italic" },
    { token: "keyword", foreground: "f4eee4" },
    { token: "string", foreground: "f87c32" },
    { token: "number", foreground: "e2777a" },
    { token: "type", foreground: "fff5f6" },
    { token: "function", foreground: "fdfdfd" },
    { token: "variable", foreground: "ff6ac1" },
    { token: "constant", foreground: "f92aad" },
    { token: "operator", foreground: "67cdcc" },
    { token: "tag", foreground: "e2777a" },
    { token: "attribute.name", foreground: "e2777a" },
    { token: "attribute.value", foreground: "f87c32" },
    { token: "delimiter", foreground: "ccc" },
    { token: "regexp", foreground: "f87c32" },
  ],
  colors: {
    "editor.background": "#2a2139",
    "editor.foreground": "#f92aad",
    "editor.lineHighlightBackground": "#34294f",
    "editor.selectionBackground": "#463465",
    "editorCursor.foreground": "#f92aad",
    "editorWhitespace.foreground": "#34294f",
    "editorLineNumber.foreground": "#6a5f7a",
    "editorLineNumber.activeForeground": "#f92aad",
    "editorIndentGuide.background": "#34294f",
    "editorIndentGuide.activeBackground": "#495495",
    "editorBracketMatch.background": "#46346580",
    "editorBracketMatch.border": "#f92aad50",
    "editor.findMatchBackground": "#f87c3244",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#2a2139",
    "scrollbarSlider.background": "#49549580",
    "scrollbarSlider.hoverBackground": "#495495a0",
    "scrollbarSlider.activeBackground": "#495495c0",
  },
};

// ── Material Dark ────────────────────────────────────────────

export const materialDark: MonacoThemeDef = {
  id: "material-dark",
  name: "Material Dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "616161", fontStyle: "italic" },
    { token: "keyword", foreground: "c792ea" },
    { token: "string", foreground: "a5e844" },
    { token: "number", foreground: "fd9170" },
    { token: "type", foreground: "f2ff00" },
    { token: "function", foreground: "c792ea" },
    { token: "variable", foreground: "ff6666" },
    { token: "constant", foreground: "c792ea" },
    { token: "operator", foreground: "89ddff" },
    { token: "tag", foreground: "ff6666" },
    { token: "attribute.name", foreground: "ffcb6b" },
    { token: "attribute.value", foreground: "a5e844" },
    { token: "delimiter", foreground: "89ddff" },
    { token: "regexp", foreground: "f2ff00" },
  ],
  colors: {
    "editor.background": "#2f2f2f",
    "editor.foreground": "#eee",
    "editor.lineHighlightBackground": "#3a3a3a",
    "editor.selectionBackground": "#363636",
    "editorCursor.foreground": "#ffcb6b",
    "editorWhitespace.foreground": "#424242",
    "editorLineNumber.foreground": "#616161",
    "editorLineNumber.activeForeground": "#eee",
    "editorIndentGuide.background": "#42424260",
    "editorIndentGuide.activeBackground": "#616161",
    "editorBracketMatch.background": "#36363680",
    "editorBracketMatch.border": "#89ddff50",
    "editor.findMatchBackground": "#ffcb6b44",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#2f2f2f",
    "scrollbarSlider.background": "#42424280",
    "scrollbarSlider.hoverBackground": "#424242a0",
    "scrollbarSlider.activeBackground": "#424242c0",
  },
};

// ── Hopscotch ────────────────────────────────────────────────

export const hopscotch: MonacoThemeDef = {
  id: "hopscotch",
  name: "Hopscotch",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "797379", fontStyle: "italic" },
    { token: "keyword", foreground: "8fc13e" },
    { token: "string", foreground: "149b93" },
    { token: "number", foreground: "fd8b19" },
    { token: "type", foreground: "fdcc59" },
    { token: "function", foreground: "fdcc59" },
    { token: "variable", foreground: "1290bf" },
    { token: "constant", foreground: "fd8b19" },
    { token: "operator", foreground: "fd8b19" },
    { token: "tag", foreground: "1290bf" },
    { token: "attribute.name", foreground: "fd8b19" },
    { token: "attribute.value", foreground: "8fc13e" },
    { token: "delimiter", foreground: "b9b5b8" },
    { token: "regexp", foreground: "149b93" },
  ],
  colors: {
    "editor.background": "#322931",
    "editor.foreground": "#b9b5b8",
    "editor.lineHighlightBackground": "#3d3244",
    "editor.selectionBackground": "#45384b",
    "editorCursor.foreground": "#b9b5b8",
    "editorWhitespace.foreground": "#45384b",
    "editorLineNumber.foreground": "#5b4a5e",
    "editorLineNumber.activeForeground": "#b9b5b8",
    "editorIndentGuide.background": "#45384b60",
    "editorIndentGuide.activeBackground": "#5b4a5e",
    "editorBracketMatch.background": "#45384b80",
    "editorBracketMatch.border": "#1290bf50",
    "editor.findMatchBackground": "#fdcc5944",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#322931",
    "scrollbarSlider.background": "#5b4a5e80",
    "scrollbarSlider.hoverBackground": "#5b4a5ea0",
    "scrollbarSlider.activeBackground": "#5b4a5ec0",
  },
};

// ── Atom Dark ────────────────────────────────────────────────

export const atomDark: MonacoThemeDef = {
  id: "atom-dark",
  name: "Atom Dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "7C7C7C", fontStyle: "italic" },
    { token: "keyword", foreground: "96CBFE" },
    { token: "string", foreground: "A8FF60" },
    { token: "number", foreground: "FF73FD" },
    { token: "type", foreground: "FFFFB6" },
    { token: "function", foreground: "DAD085" },
    { token: "variable", foreground: "C6C5FE" },
    { token: "constant", foreground: "99CC99" },
    { token: "operator", foreground: "EDEDED" },
    { token: "tag", foreground: "96CBFE" },
    { token: "attribute.name", foreground: "96CBFE" },
    { token: "attribute.value", foreground: "F9EE98" },
    { token: "delimiter", foreground: "c5c8c6" },
    { token: "regexp", foreground: "E9C062" },
  ],
  colors: {
    "editor.background": "#1d1f21",
    "editor.foreground": "#c5c8c6",
    "editor.lineHighlightBackground": "#2c2e30",
    "editor.selectionBackground": "#373b41",
    "editorCursor.foreground": "#c5c8c6",
    "editorWhitespace.foreground": "#373b41",
    "editorLineNumber.foreground": "#5a5a5a",
    "editorLineNumber.activeForeground": "#c5c8c6",
    "editorIndentGuide.background": "#373b4160",
    "editorIndentGuide.activeBackground": "#5a5a5a",
    "editorBracketMatch.background": "#373b4180",
    "editorBracketMatch.border": "#96CBFE50",
    "editor.findMatchBackground": "#FFFFB644",
    "editor.findMatchHighlightBackground": "#ffffff18",
    "editorOverviewRuler.border": "#1d1f21",
    "scrollbarSlider.background": "#383a3e80",
    "scrollbarSlider.hoverBackground": "#383a3ea0",
    "scrollbarSlider.activeBackground": "#383a3ec0",
  },
};

// ── VS Code Dark+ ────────────────────────────────────────────

export const vscDarkPlus: MonacoThemeDef = {
  id: "vsc-dark-plus",
  name: "VS Code Dark+",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6a9955", fontStyle: "italic" },
    { token: "keyword", foreground: "569CD6" },
    { token: "string", foreground: "ce9178" },
    { token: "number", foreground: "b5cea8" },
    { token: "type", foreground: "4ec9b0" },
    { token: "function", foreground: "dcdcaa" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "constant", foreground: "9cdcfe" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "tag", foreground: "569cd6" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "ce9178" },
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "regexp", foreground: "d16969" },
  ],
  colors: {
    "editor.background": "#1e1e1e",
    "editor.foreground": "#d4d4d4",
    "editor.lineHighlightBackground": "#2a2d2e",
    "editor.selectionBackground": "#264F78",
    "editorCursor.foreground": "#d4d4d4",
    "editorWhitespace.foreground": "#3b3b3b",
    "editorLineNumber.foreground": "#858585",
    "editorLineNumber.activeForeground": "#c6c6c6",
    "editorIndentGuide.background": "#40404060",
    "editorIndentGuide.activeBackground": "#707070",
    "editorBracketMatch.background": "#264F7850",
    "editorBracketMatch.border": "#569cd650",
    "editor.findMatchBackground": "#515c6a",
    "editor.findMatchHighlightBackground": "#ea5c0055",
    "editorOverviewRuler.border": "#1e1e1e",
    "scrollbarSlider.background": "#79797966",
    "scrollbarSlider.hoverBackground": "#64646480",
    "scrollbarSlider.activeBackground": "#bfbfbf66",
  },
};

// ── All built-in themes ──────────────────────────────────────

export const BUILT_IN_THEMES: MonacoThemeDef[] = [
  oneDark,
  dracula,
  githubDark,
  monokai,
  nord,
  synthwave84,
  materialDark,
  hopscotch,
  atomDark,
  vscDarkPlus,
];
