/**
 * @module editor/themes/defaults
 * Seven built-in editor themes with full color, syntax, and font definitions.
 *
 * Each theme follows the EditorTheme interface and is marked `isBuiltIn: true`
 * so the Theme Manager knows they cannot be deleted by users.
 */
import type { EditorTheme, ThemeColors, ThemeFont, ThemeSyntax } from "../types";

// ── Shared font presets ──────────────────────────────────────

const MONO_FONT: ThemeFont = {
    family: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace",
    size: 13,
    weight: 400,
    lineHeight: 20,
    cursorStyle: "line",
};

// ═══════════════════════════════════════════════════════════════
// 1. Dracula
// ═══════════════════════════════════════════════════════════════

const draculaColors: ThemeColors = {
    background: "#282a36",
    foreground: "#f8f8f2",
    selection: "#44475a99",
    cursor: "#f8f8f2",
    lineHighlight: "#44475a40",
    gutterFg: "#6272a4",
    gutterActiveFg: "#f8f8f2",
    gutterBg: "#282a36",
    border: "#44475a",
    scrollbarThumb: "#44475a",
    scrollbarThumbHover: "#6272a4",
    scrollbarTrack: "#21222c",
    toolbarBg: "#21222c",
    statusBarBg: "#191a21",
    inputBg: "#282a36",
    inputBorder: "#44475a",
    inputFocusBorder: "#bd93f9",
    accent: "#bd93f9",
    accentHover: "#caa9fa",
    accentFg: "#282a36",
    success: "#50fa7b",
    warning: "#ffb86c",
    error: "#ff5555",
    info: "#6272a4",
    muted: "#6272a4",
    popupBg: "#21222c",
    popupHoverBg: "#44475a",
};

const draculaSyntax: ThemeSyntax = {
    keyword: "#ff79c6",
    string: "#f1fa8c",
    number: "#bd93f9",
    comment: "#6272a4",
    operator: "#f8f8f2",
    function: "#50fa7b",
    className: "#50fa7b",
    variable: "#ffb86c",
    property: "#ff79c6",
    tag: "#ff79c6",
    attribute: "#f1fa8c",
    constant: "#bd93f9",
    regex: "#ffb86c",
    punctuation: "#f8f8f2",
    builtin: "#8be9fd",
    inserted: "#50fa7b",
    deleted: "#ff5555",
    important: "#ffb86c",
    doctype: "#6272a4",
};

export const dracula: EditorTheme = {
    id: "dracula",
    name: "Dracula",
    type: "dark",
    colors: draculaColors,
    syntax: draculaSyntax,
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 2. VS Code Dark+
// ═══════════════════════════════════════════════════════════════

export const vsDark: EditorTheme = {
    id: "vs-dark",
    name: "VS Dark",
    type: "dark",
    colors: {
        background: "#1e1e1e",
        foreground: "#d4d4d4",
        selection: "#264f78aa",
        cursor: "#aeafad",
        lineHighlight: "#2a2d2e",
        gutterFg: "#858585",
        gutterActiveFg: "#c6c6c6",
        gutterBg: "#1e1e1e",
        border: "#3c3c3c",
        scrollbarThumb: "#424242",
        scrollbarThumbHover: "#4f4f4f",
        scrollbarTrack: "#1e1e1e",
        toolbarBg: "#252526",
        statusBarBg: "#007acc",
        inputBg: "#3c3c3c",
        inputBorder: "#3c3c3c",
        inputFocusBorder: "#007acc",
        accent: "#007acc",
        accentHover: "#1a8ad4",
        accentFg: "#ffffff",
        success: "#4ec9b0",
        warning: "#cca700",
        error: "#f44747",
        info: "#858585",
        muted: "#858585",
        popupBg: "#252526",
        popupHoverBg: "#094771",
    },
    syntax: {
        keyword: "#c586c0",
        string: "#ce9178",
        number: "#b5cea8",
        comment: "#6a9955",
        operator: "#d4d4d4",
        function: "#dcdcaa",
        className: "#4ec9b0",
        variable: "#9cdcfe",
        property: "#9cdcfe",
        tag: "#569cd6",
        attribute: "#9cdcfe",
        constant: "#4fc1ff",
        regex: "#d16969",
        punctuation: "#d4d4d4",
        builtin: "#4ec9b0",
        inserted: "#b5cea8",
        deleted: "#ce9178",
        important: "#569cd6",
        doctype: "#6a9955",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 3. Monokai
// ═══════════════════════════════════════════════════════════════

export const monokai: EditorTheme = {
    id: "monokai",
    name: "Monokai",
    type: "dark",
    colors: {
        background: "#272822",
        foreground: "#f8f8f2",
        selection: "#49483eaa",
        cursor: "#f8f8f0",
        lineHighlight: "#3e3d3240",
        gutterFg: "#90908a",
        gutterActiveFg: "#f8f8f2",
        gutterBg: "#272822",
        border: "#3e3d32",
        scrollbarThumb: "#49483e",
        scrollbarThumbHover: "#75715e",
        scrollbarTrack: "#272822",
        toolbarBg: "#1e1f1c",
        statusBarBg: "#1e1f1c",
        inputBg: "#3e3d32",
        inputBorder: "#3e3d32",
        inputFocusBorder: "#a6e22e",
        accent: "#a6e22e",
        accentHover: "#b8f336",
        accentFg: "#272822",
        success: "#a6e22e",
        warning: "#e6db74",
        error: "#f92672",
        info: "#75715e",
        muted: "#75715e",
        popupBg: "#1e1f1c",
        popupHoverBg: "#3e3d32",
    },
    syntax: {
        keyword: "#f92672",
        string: "#e6db74",
        number: "#ae81ff",
        comment: "#75715e",
        operator: "#f92672",
        function: "#a6e22e",
        className: "#a6e22e",
        variable: "#f8f8f2",
        property: "#a6e22e",
        tag: "#f92672",
        attribute: "#a6e22e",
        constant: "#ae81ff",
        regex: "#e6db74",
        punctuation: "#f8f8f2",
        builtin: "#66d9ef",
        inserted: "#a6e22e",
        deleted: "#f92672",
        important: "#fd971f",
        doctype: "#75715e",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 4. One Dark
// ═══════════════════════════════════════════════════════════════

export const oneDark: EditorTheme = {
    id: "one-dark",
    name: "One Dark",
    type: "dark",
    colors: {
        background: "#282c34",
        foreground: "#abb2bf",
        selection: "#3e4451aa",
        cursor: "#528bff",
        lineHighlight: "#2c313a",
        gutterFg: "#636d83",
        gutterActiveFg: "#abb2bf",
        gutterBg: "#282c34",
        border: "#3e4451",
        scrollbarThumb: "#3e4451",
        scrollbarThumbHover: "#636d83",
        scrollbarTrack: "#282c34",
        toolbarBg: "#21252b",
        statusBarBg: "#21252b",
        inputBg: "#1d2025",
        inputBorder: "#3e4451",
        inputFocusBorder: "#528bff",
        accent: "#528bff",
        accentHover: "#6da0ff",
        accentFg: "#ffffff",
        success: "#98c379",
        warning: "#e5c07b",
        error: "#e06c75",
        info: "#636d83",
        muted: "#636d83",
        popupBg: "#21252b",
        popupHoverBg: "#2c313a",
    },
    syntax: {
        keyword: "#c678dd",
        string: "#98c379",
        number: "#d19a66",
        comment: "#5c6370",
        operator: "#56b6c2",
        function: "#61afef",
        className: "#e5c07b",
        variable: "#e06c75",
        property: "#e06c75",
        tag: "#e06c75",
        attribute: "#d19a66",
        constant: "#d19a66",
        regex: "#98c379",
        punctuation: "#abb2bf",
        builtin: "#56b6c2",
        inserted: "#98c379",
        deleted: "#e06c75",
        important: "#c678dd",
        doctype: "#5c6370",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 5. Darcula (JetBrains)
// ═══════════════════════════════════════════════════════════════

export const darcula: EditorTheme = {
    id: "darcula",
    name: "Darcula",
    type: "dark",
    colors: {
        background: "#2b2b2b",
        foreground: "#a9b7c6",
        selection: "#214283aa",
        cursor: "#a9b7c6",
        lineHighlight: "#323232",
        gutterFg: "#606366",
        gutterActiveFg: "#a4a3a3",
        gutterBg: "#2b2b2b",
        border: "#3c3f41",
        scrollbarThumb: "#3c3f41",
        scrollbarThumbHover: "#555555",
        scrollbarTrack: "#2b2b2b",
        toolbarBg: "#3c3f41",
        statusBarBg: "#3c3f41",
        inputBg: "#45494a",
        inputBorder: "#5e6164",
        inputFocusBorder: "#3592c4",
        accent: "#3592c4",
        accentHover: "#47a7db",
        accentFg: "#ffffff",
        success: "#6a8759",
        warning: "#bbb529",
        error: "#ff6b68",
        info: "#606366",
        muted: "#606366",
        popupBg: "#3c3f41",
        popupHoverBg: "#4b6eaf30",
    },
    syntax: {
        keyword: "#cc7832",
        string: "#6a8759",
        number: "#6897bb",
        comment: "#808080",
        operator: "#a9b7c6",
        function: "#ffc66d",
        className: "#a9b7c6",
        variable: "#a9b7c6",
        property: "#9876aa",
        tag: "#e8bf6a",
        attribute: "#bababa",
        constant: "#6897bb",
        regex: "#6a8759",
        punctuation: "#a9b7c6",
        builtin: "#8888c6",
        inserted: "#6a8759",
        deleted: "#ff6b68",
        important: "#cc7832",
        doctype: "#808080",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 6. Solarized Dark
// ═══════════════════════════════════════════════════════════════

export const solarizedDark: EditorTheme = {
    id: "solarized-dark",
    name: "Solarized Dark",
    type: "dark",
    colors: {
        background: "#002b36",
        foreground: "#839496",
        selection: "#073642cc",
        cursor: "#839496",
        lineHighlight: "#073642",
        gutterFg: "#586e75",
        gutterActiveFg: "#93a1a1",
        gutterBg: "#002b36",
        border: "#073642",
        scrollbarThumb: "#073642",
        scrollbarThumbHover: "#586e75",
        scrollbarTrack: "#002b36",
        toolbarBg: "#073642",
        statusBarBg: "#073642",
        inputBg: "#073642",
        inputBorder: "#586e75",
        inputFocusBorder: "#268bd2",
        accent: "#268bd2",
        accentHover: "#2aa0f0",
        accentFg: "#fdf6e3",
        success: "#859900",
        warning: "#b58900",
        error: "#dc322f",
        info: "#586e75",
        muted: "#586e75",
        popupBg: "#073642",
        popupHoverBg: "#002b36",
    },
    syntax: {
        keyword: "#859900",
        string: "#2aa198",
        number: "#d33682",
        comment: "#586e75",
        operator: "#839496",
        function: "#268bd2",
        className: "#b58900",
        variable: "#268bd2",
        property: "#268bd2",
        tag: "#268bd2",
        attribute: "#93a1a1",
        constant: "#cb4b16",
        regex: "#dc322f",
        punctuation: "#839496",
        builtin: "#d33682",
        inserted: "#859900",
        deleted: "#dc322f",
        important: "#cb4b16",
        doctype: "#586e75",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 7. GitHub Dark
// ═══════════════════════════════════════════════════════════════

export const githubDark: EditorTheme = {
    id: "github-dark",
    name: "GitHub Dark",
    type: "dark",
    colors: {
        background: "#0d1117",
        foreground: "#e6edf3",
        selection: "#264f78aa",
        cursor: "#e6edf3",
        lineHighlight: "#161b22",
        gutterFg: "#6e7681",
        gutterActiveFg: "#e6edf3",
        gutterBg: "#0d1117",
        border: "#30363d",
        scrollbarThumb: "#30363d",
        scrollbarThumbHover: "#484f58",
        scrollbarTrack: "#0d1117",
        toolbarBg: "#161b22",
        statusBarBg: "#161b22",
        inputBg: "#0d1117",
        inputBorder: "#30363d",
        inputFocusBorder: "#58a6ff",
        accent: "#58a6ff",
        accentHover: "#79c0ff",
        accentFg: "#0d1117",
        success: "#3fb950",
        warning: "#d29922",
        error: "#f85149",
        info: "#6e7681",
        muted: "#6e7681",
        popupBg: "#161b22",
        popupHoverBg: "#30363d",
    },
    syntax: {
        keyword: "#ff7b72",
        string: "#a5d6ff",
        number: "#79c0ff",
        comment: "#8b949e",
        operator: "#e6edf3",
        function: "#d2a8ff",
        className: "#f0883e",
        variable: "#ffa657",
        property: "#79c0ff",
        tag: "#7ee787",
        attribute: "#79c0ff",
        constant: "#79c0ff",
        regex: "#a5d6ff",
        punctuation: "#e6edf3",
        builtin: "#ffa657",
        inserted: "#aff5b4",
        deleted: "#ffa198",
        important: "#ff7b72",
        doctype: "#8b949e",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 8. VS Dark 2 (VS Code Dark+ faithful port)
// ═══════════════════════════════════════════════════════════════

export const vsDark2: EditorTheme = {
    id: "vs-dark-2",
    name: "VS Dark 2",
    type: "dark",
    colors: {
        background: "#1e1e1e",
        foreground: "#d4d4d4",
        selection: "#264f78aa",
        cursor: "#aeafad",
        lineHighlight: "#2a2d2e",
        gutterFg: "#858585",
        gutterActiveFg: "#c6c6c6",
        gutterBg: "#1e1e1e",
        border: "#3c3c3c",
        scrollbarThumb: "#424242",
        scrollbarThumbHover: "#4f4f4f",
        scrollbarTrack: "#1e1e1e",
        toolbarBg: "#252526",
        statusBarBg: "#007acc",
        inputBg: "#3c3c3c",
        inputBorder: "#3c3c3c",
        inputFocusBorder: "#007acc",
        accent: "#007acc",
        accentHover: "#1a8ad4",
        accentFg: "#ffffff",
        success: "#4ec9b0",
        warning: "#cca700",
        error: "#f44747",
        info: "#858585",
        muted: "#858585",
        popupBg: "#252526",
        popupHoverBg: "#094771",
    },
    syntax: {
        keyword: "#569cd6",
        string: "#ce9178",
        number: "#b5cea8",
        comment: "#6a9955",
        operator: "#d4d4d4",
        function: "#dcdcaa",
        className: "#4ec9b0",
        variable: "#9cdcfe",
        property: "#9cdcfe",
        tag: "#569cd6",
        attribute: "#9cdcfe",
        constant: "#9cdcfe",
        regex: "#d16969",
        punctuation: "#d4d4d4",
        builtin: "#4ec9b0",
        inserted: "#b5cea8",
        deleted: "#ce9178",
        important: "#569cd6",
        doctype: "#6a9955",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// 9. Synthwave '84
// ═══════════════════════════════════════════════════════════════

export const synthwave84: EditorTheme = {
    id: "synthwave-84",
    name: "Synthwave '84",
    type: "dark",
    colors: {
        background: "#2a2139",
        foreground: "#f92aad",
        selection: "#463465bb",
        cursor: "#f92aad",
        lineHighlight: "#34294f",
        gutterFg: "#6e5a8e",
        gutterActiveFg: "#f92aad",
        gutterBg: "#2a2139",
        border: "#34294f",
        scrollbarThumb: "#463465",
        scrollbarThumbHover: "#6e5a8e",
        scrollbarTrack: "#2a2139",
        toolbarBg: "#241b2f",
        statusBarBg: "#241b2f",
        inputBg: "#34294f",
        inputBorder: "#463465",
        inputFocusBorder: "#f92aad",
        accent: "#f92aad",
        accentHover: "#ff6bcb",
        accentFg: "#2a2139",
        success: "#72f1b8",
        warning: "#f87c32",
        error: "#e2777a",
        info: "#6e5a8e",
        muted: "#8e8e8e",
        popupBg: "#241b2f",
        popupHoverBg: "#34294f",
    },
    syntax: {
        keyword: "#f4eee4",
        string: "#f87c32",
        number: "#e2777a",
        comment: "#8e8e8e",
        operator: "#67cdcc",
        function: "#fdfdfd",
        className: "#fff5f6",
        variable: "#f87c32",
        property: "#72f1b8",
        tag: "#e2777a",
        attribute: "#e2777a",
        constant: "#f92aad",
        regex: "#f87c32",
        punctuation: "#cccccc",
        builtin: "#f4eee4",
        inserted: "#72f1b8",
        deleted: "#e2777a",
        important: "#f4eee4",
        doctype: "#8e8e8e",
    },
    font: { ...MONO_FONT },
    isBuiltIn: true,
};

// ═══════════════════════════════════════════════════════════════
// Registry of all built-in themes
// ═══════════════════════════════════════════════════════════════

export const BUILT_IN_THEMES: EditorTheme[] = [
    dracula,
    vsDark,
    
    monokai,
    oneDark,
    darcula,
    solarizedDark,
    githubDark,
    synthwave84,
];

/** Union of all built-in theme IDs for type-safe props */
export type BuiltInThemeId =
    | "dracula"
    | "vs-dark"
    | "monokai"
    | "one-dark"
    | "darcula"
    | "solarized-dark"
    | "github-dark"
    | "synthwave-84";
